image:
    file: .gitpod.Dockerfile
tasks:
    - name: tailscaled
      command: |
          if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
            # restore the tailscale state from gitpod user's env vars
            sudo mkdir -p /var/lib/tailscale
            echo "${TS_STATE_TAILSCALE_EXAMPLE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
          fi
          sudo tailscaled
    - name: tailscale
      command: |
          sudo -E tailscale up --hostname "gitpod@nooobcoder-${GITPOD_WORKSPACE_ID}" \
                              --authkey "${TAILSCALE_AUTHKEY}"
    - name: Import GPG
      init: >
          [[ ! -z $GNUPG_KEY  ]] &&
          gpg --verbose --batch --import <(echo $GNUPG_KEY|base64 -d) &&
          echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf &&
          git config commit.gpgsign true &&
          ./install.sh
